### PR TITLE
format invalid hash error

### LINKED ISSUE #1276: "Merkle Hash Invalid" Error code is very vague
**Describe the bug**
Need a more descriptive error code on the invalid hash

### PR DESCRIPTION
**Pull request by edjroz**
Close #1276

### CODE REVIEW

**Review by andrewnguyen22 — DISMISSED** [review]

File: x/pocketcore/types/errors.go [hunk 1]
```diff
@@ -128,7 +130,7 @@ var (
 	FilterNodesError                 = errors.New("unable to filter nodes: ")
 	XORError                         = errors.New("error XORing the keys: ")
 	PubKeyDecodeError                = errors.New("error decoding the string into hex bytes")
-	InvalidHashError                 = errors.New("the merkleHash is invalid: ")
+	InvalidHashError                 = errors.New("the hash ")
```
Comment (andrewnguyen22) [inline x/pocketcore/types/errors.go]: I feel like this should say: " hash is invalid: "

File: x/pocketcore/types/errors.go [hunk 2]
```diff
@@ -411,8 +413,9 @@ func NewEmptyPayloadDataError(codespace sdk.CodespaceType) sdk.Error {
 	return sdk.NewError(codespace, CodeEmptyPayloadDataError, EmptyPayloadDataError.Error())
 }
 
-func NewInvalidHashError(codespace sdk.CodespaceType, err error) sdk.Error {
-	return sdk.NewError(codespace, CodeInvalidHashError, InvalidHashError.Error()+err.Error())
+func NewInvalidHashError(codespace sdk.CodespaceType, err error, h string) sdk.Error {
+	InvalidHash := fmt.Sprintf("%s %s is invalid due to: %s", InvalidHashError.Error(), h, err.Error())
```
Comment (andrewnguyen22) [inline x/pocketcore/types/errors.go]: I'd like to move the error message to the variabel

then just sprintf `fmt.Sprintf("%s %s %s, h, InvalidHashError.Error(), err.Error())`

Comment (edjroz) [reply x/pocketcore/types/errors.go]: `fmt.Sprintf("%s %s%s", ....)` since the msg error is `"the hash is invalid: "`

**Review by andrewnguyen22 — APPROVED** [review]
