### PR TITLE
Fix for reset cmd on new configuration model

### LINKED ISSUE #789: Update Reset Command for new config
on _latest_ the reset command is not working

### PR DESCRIPTION
**Pull request by oten91**
closes #789

### CODE REVIEW

File: app/config.go [hunk 1]
```diff
@@ -681,14 +681,30 @@ func createDummyACL(kp crypto.PublicKey) govTypes.ACL {
...
+		if err != nil {
+			panic("could not get home directory for data dir creation: " + err.Error())
+		}
+		datadir = home + FS + DefaultDDName
+	} else {
+		datadir = cmd.Flag("datadir").Value.String()
+	}
+	c := DefaultConfig(datadir)
+	GlobalConfig = c
+}
```
Comment (edjroz) [inline app/config.go]: This looks very specific to the reset CLI, can we just put this inside the Reset WorldState ?

**Review by edjroz — DISMISSED** [review]

File: app/config.go (hunk 1 above)
Comment (oten91) [reply app/config.go]: sure

**Review by edjroz — APPROVED** [review]
