### PR TITLE
removed all panics from source code

### LINKED ISSUE #869: No panics in source code
**Describe the bug**
Remove all panics from the source code. If need to exit, gracefully exit

### PR DESCRIPTION
**Pull request by andrewnguyen22**
closes #869

### CODE REVIEW

**Comment by andrewnguyen22** [comment]
I know it's big, but please review carefully @edjroz @oten91 @luyzdeleon

File: app/cmd/rpc/server.go [hunk 1]
```diff
@@ -87,12 +87,12 @@ func WriteResponse(w http.ResponseWriter, jsn, path, ip string) {
 	b, err := json.Marshal(jsn)
 	if err != nil {
 		WriteErrorResponse(w, http.StatusInternalServerError, err.Error())
-		log.Println(err.Error())
+		fmt.Println(err.Error())
```
Comment (edjroz) [inline app/cmd/rpc/server.go:90]: should consider using log instead of fmt, log adds a timestamp to the message being printed.

File: x/pocketcore/types/proof.go [hunk 2]
```diff
@@ -419,7 +422,8 @@ func (c ChallengeProofInvalidData) Bytes() []byte {
 		},
 	})
 	if err != nil {
-		panic(fmt.Sprintf("an error occured converting the challengeproof to bytes\n%v", err))
+		fmt.Println(fmt.Errorf("an error occured converting the challengeproof to bytes\n%v", err))
+		os.Exit(1)
```
Comment (edjroz) [inline x/pocketcore/types/proof.go]:
```suggestion
  log.Fatalf("an error occured converting the relay challengeproof to bytes:\n%v", err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

File: x/pocketcore/types/proof.go [hunk 3]
```diff
@@ -169,7 +171,8 @@ func (rp RelayProof) BytesWithSignature() []byte {
 		Token:              rp.Token.HashString(),
 	})
 	if err != nil {
-		panic(fmt.Sprintf("an error occured converting the relay RelayProof to bytes with signature:\n%v", err))
+		fmt.Println(fmt.Errorf("an error occured converting the relay RelayProof to bytesWithSignature:\n%v", err))
+		os.Exit(1)
```
Comment (edjroz) [inline x/pocketcore/types/proof.go]:
```suggestion
  log.Fatalf("an error occured converting the relay RelayProof to bytesWithSignature:\n%v", err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

File: x/pocketcore/types/proof.go [hunk 4]
```diff
@@ -152,7 +153,8 @@ func (rp RelayProof) Bytes() []byte {
 		Token:              rp.Token.HashString(),
 	})
 	if err != nil {
-		panic(fmt.Sprintf("an error occured converting the relay RelayProof to bytes:\n%v", err))
+		fmt.Println(fmt.Errorf("an error occured converting the relay RelayProof to bytes:\n%v", err))
+		os.Exit(1)
```
Comment (edjroz) [inline x/pocketcore/types/proof.go]:
```suggestion
  log.Fatalf("an error occured converting the relay RelayProof to bytes:\n%v", err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

File: x/pocketcore/types/service.go [hunk 5]
```diff
@@ -130,7 +131,8 @@ func (r Relay) RequestHash() []byte {
 	}{r.Payload, r.Meta}
 	res, err := json.Marshal(relay)
 	if err != nil {
-		panic(fmt.Sprintf("cannot marshal relay request hash: %s", err.Error()))
+		fmt.Println(fmt.Errorf("cannot marshal relay request hash: %s", err.Error()))
+		os.Exit(1)
```
Comment (edjroz) [inline x/pocketcore/types/service.go]:
```suggestion
  log.Fatalf("cannot marshal relay request hash: %s", err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

File: x/pocketcore/types/service.go [hunk 6]
```diff
@@ -152,7 +154,8 @@ type Payload struct {
 func (p Payload) Bytes() []byte {
 	bz, err := json.Marshal(p)
 	if err != nil {
-		panic(fmt.Sprintf("an error occured converting the payload to bytes:\n%v", err))
+		fmt.Println(fmt.Errorf("an error occured converting the payload to bytes:\n%v", err))
+		os.Exit(1)
```
Comment (edjroz) [inline x/pocketcore/types/service.go]:
```suggestion
  log.Fatalf("an error occured converting the payload to bytes:\n%v", err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

File: x/pocketcore/types/service.go [hunk 7]
```diff
@@ -240,7 +243,8 @@ func (rr RelayResponse) Hash() []byte {
 		Proof:     rr.Proof.HashString(),
 	})
 	if err != nil {
-		panic(fmt.Sprintf("an error occured hashing the relay response:\n%v", err))
+		fmt.Println(fmt.Errorf("an error occured hashing the relay response:\n%v", err))
+		os.Exit(1)
```
Comment (edjroz) [inline x/pocketcore/types/service.go]:
```suggestion
  log.Fatalf("an error occured hashing the relay response:\n%v", err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

File: x/pocketcore/types/session.go [hunk 8]
```diff
@@ -7,6 +7,7 @@ import (
 	appexported "github.com/pokt-network/pocket-core/x/apps/exported"
 	nodeexported "github.com/pokt-network/pocket-core/x/nodes/exported"
 	sdk "github.com/pokt-network/posmint/types"
+	"os"
```
Comment (edjroz) [inline x/pocketcore/types/session.go]:
```suggestion
	"log"
```

File: x/pocketcore/types/session.go [hunk 9]
```diff
@@ -255,7 +256,8 @@ func (sh SessionHeader) HashString() string {
 func (sh SessionHeader) Bytes() []byte {
 	res, err := json.Marshal(sh)
 	if err != nil {
-		panic(fmt.Sprintf("an error occured converting the session header into bytes:\n%v", err))
+		fmt.Println(fmt.Errorf("an error occured converting the session header into bytes:\n%v", err))
+		os.Exit(1)
```
Comment (edjroz) [inline x/pocketcore/types/session.go]:
```suggestion
  log.Fatalf("an error occured converting the session header into bytes:\n%v", err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

File: x/pocketcore/types/service.go [hunk 10]
```diff
@@ -8,6 +8,7 @@ import (
 	"io/ioutil"
 	"math"
 	"net/http"
+	"os"
```
Comment (edjroz) [inline x/pocketcore/types/service.go]:
```suggestion
	"log"
```

File: x/pocketcore/types/proof.go [hunk 11]
```diff
@@ -7,6 +7,7 @@ import (
 	"github.com/pokt-network/posmint/crypto"
 	sdk "github.com/pokt-network/posmint/types"
 	"math"
+	"os"
```
Comment (edjroz) [inline x/pocketcore/types/proof.go]:
```suggestion
	"log"
```

File: x/pocketcore/types/cache.go [hunk 12]
```diff
@@ -6,6 +6,7 @@ import (
 	lru "github.com/hashicorp/golang-lru"
 	db "github.com/tendermint/tm-db"
 	"github.com/willf/bloom"
+	"os"
```
Comment (edjroz) [inline x/pocketcore/types/cache.go]:
```suggestion
	"log"
```

File: x/pocketcore/types/cache.go [hunk 13]
```diff
@@ -41,7 +42,8 @@ func (cs *CacheStorage) Init(dir, name string, dbType db.DBBackendType, maxEntri
 	var err error
 	cs.Cache, err = lru.New(maxEntries)
 	if err != nil {
-		panic(err)
+		fmt.Println(fmt.Errorf("could not initialize cache storage: " + err.Error()))
+		os.Exit(1)
```
Comment (edjroz) [inline x/pocketcore/types/cache.go]:
```suggestion
  log.Fatalf("could not initialize cache storage: %s", err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

File: x/pocketcore/types/cache.go [hunk 14]
```diff
@@ -161,7 +165,8 @@ type SessionIt struct {
 func (si *SessionIt) Value() (session Session) {
 	err := ModuleCdc.UnmarshalJSON(si.Iterator.Value(), &session)
 	if err != nil {
-		panic(fmt.Errorf("can't unmarshal session iterator value into session: %s", err.Error()))
+		fmt.Println(fmt.Errorf("can't unmarshal session iterator value into session: %s", err.Error()))
+		os.Exit(1)
```
Comment (edjroz) [inline x/pocketcore/types/cache.go]:
```suggestion
  log.Fatalf("can't unmarshal session iterator value into session: %s", err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

File: x/pocketcore/types/cache.go [hunk 15]
```diff
@@ -238,7 +245,8 @@ func (ei *EvidenceIt) Value() (evidence Evidence) {
 	// unmarshal the value (bz) into an evidence object
 	err := ModuleCdc.UnmarshalJSON(ei.Iterator.Value(), &evidence)
 	if err != nil {
-		panic(fmt.Errorf("can't unmarshal evidence iterator value into evidence: %s", err.Error()))
+		fmt.Println(fmt.Errorf("can't unmarshal evidence iterator value into evidence: %s", err.Error()))
+		os.Exit(1)
```
Comment (edjroz) [inline x/pocketcore/types/cache.go]:
```suggestion
  log.Fatalf("can't unmarshal evidence iterator value into evidence: %s", err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

File: x/pocketcore/types/aat.go [hunk 16]
```diff
@@ -4,6 +4,7 @@ import (
 	"encoding/hex"
 	"encoding/json"
 	"fmt"
+	"os"
```
Comment (edjroz) [inline x/pocketcore/types/aat.go]:
```suggestion
	"log"
```

File: x/pocketcore/types/aat.go [hunk 17]
```diff
@@ -66,7 +67,8 @@ func (a AAT) Bytes() []byte {
 		Version:              a.Version,
 	})
 	if err != nil {
-		panic(fmt.Sprintf("an error occured hashing the aat:\n%v", err))
+		fmt.Println(fmt.Sprintf("an error occured hashing the aat:\n%v", err))
+		os.Exit(1)
```
Comment (edjroz) [inline x/pocketcore/types/aat.go]:
```suggestion
  log.Fatalf("an error occured hashing the aat:\n%v", err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

File: x/nodes/types/valUtil.go [hunk 18]
```diff
@@ -4,6 +4,7 @@ import (
 	"encoding/hex"
 	"encoding/json"
 	"fmt"
+	"os"
```
Comment (edjroz) [inline x/nodes/types/valUtil.go:8]:
```suggestion
	"log"
```

File: x/nodes/types/valUtil.go [hunk 19]
```diff
@@ -42,7 +43,8 @@ func MustMarshalValidator(cdc *codec.Codec, validator Validator) []byte {
 func MustUnmarshalValidator(cdc *codec.Codec, valBytes []byte) Validator {
 	validator, err := UnmarshalValidator(cdc, valBytes)
 	if err != nil {
-		panic(err)
+		fmt.Println("Cannot unmarshal validator with bytes: ", hex.EncodeToString(valBytes))
+		os.Exit(1)
```
Comment (edjroz) [inline x/nodes/types/valUtil.go]:
```suggestion
  log.Fatalf("cannot unmarshal validator with bytes: %s", hex.EncodeToString(valBytes))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

File: x/apps/keeper/keeper.go [hunk 20]
```diff
@@ -3,6 +3,7 @@ package keeper
 import (
 	"container/list"
 	"fmt"
+	"os"
```
Comment (edjroz) [inline x/apps/keeper/keeper.go]:
```suggestion
	"log"
```

File: x/apps/keeper/keeper.go [hunk 21]
```diff
@@ -35,7 +36,8 @@ func NewKeeper(cdc *codec.Codec, key sdk.StoreKey, posKeeper types.PosKeeper, su
 
 	// ensure staked module accounts are set
 	if addr := supplyKeeper.GetModuleAddress(types.StakedPoolName); addr == nil {
-		panic(fmt.Sprintf("%s module account has not been set", types.StakedPoolName))
+		fmt.Println(fmt.Errorf("%s module account has not been set", types.StakedPoolName))
+		os.Exit(1)
```
Comment (edjroz) [inline x/apps/keeper/keeper.go]:
```suggestion
  log.Fatalf("%s module account has not been set", types.StakedPoolName)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

File: x/apps/genesis.go [hunk 22]
```diff
@@ -32,17 +34,20 @@ func InitGenesis(ctx sdk.Ctx, keeper keeper.Keeper, supplyKeeper types.AuthKeepe
 	// check if the staked pool accounts exists
 	stakedPool := keeper.GetStakedPool(ctx)
 	if stakedPool == nil {
-		panic(fmt.Sprintf("%s module account has not been set", types.StakedPoolName))
+		fmt.Println(fmt.Sprintf("%s module account has not been set", types.StakedPoolName))
+		os.Exit(1)
```
Comment (edjroz) [inline x/apps/genesis.go]:
```suggestion
  log.Fatalf("%s module account has not been set", types.StakedPoolName)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

File: x/apps/genesis.go [hunk 23]
```diff
@@ -5,6 +5,7 @@ import (
 	"github.com/pokt-network/pocket-core/x/apps/keeper"
 	"github.com/pokt-network/pocket-core/x/apps/types"
 	sdk "github.com/pokt-network/posmint/types"
+	"os"
```
Comment (edjroz) [inline x/apps/genesis.go]:
```suggestion
	"log"
```

File: app/util.go [hunk 24]
```diff
@@ -3,11 +3,13 @@ package app
 import (
 	"encoding/hex"
 	"encoding/json"
+	"fmt"
 	pocket "github.com/pokt-network/pocket-core/x/pocketcore"
 	"github.com/pokt-network/posmint/crypto"
 	sdk "github.com/pokt-network/posmint/types"
 	"github.com/pokt-network/posmint/x/gov"
 	"github.com/tendermint/tendermint/types"
+	"os"
```
Comment (edjroz) [inline app/util.go]:
```suggestion
	"log"
```

File: app/util.go [hunk 25]
```diff
@@ -84,11 +86,13 @@ func SortJSON(toSortJSON []byte) string {
 	var c interface{}
 	err := json.Unmarshal(toSortJSON, &c)
 	if err != nil {
-		panic(err)
+		fmt.Println("could not unmarshal json in SortJSON: " + err.Error())
+		os.Exit(1)
```
Comment (edjroz) [inline app/util.go]:
```suggestion
  log.Fatalf("could not unmarshal json in SortJSON: %s",  err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

File: app/util.go [hunk 26]
```diff
@@ -84,11 +86,13 @@ func SortJSON(toSortJSON []byte) string {
...
 	}
 	js, err := json.MarshalIndent(c, "", "    ")
 	if err != nil {
-		panic(err)
+		fmt.Println("could not marshal back to json in SortJSON: " + err.Error())
+		os.Exit(1)
```
Comment (edjroz) [inline app/util.go]:
```suggestion
  log.Fatalf("could not marshal back to json in SortJSON: %s",  err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

File: app/config.go [hunk 27]
```diff
@@ -164,7 +164,8 @@ func InitConfig(datadir, tmNode, persistentPeers, seeds, tmRPCPort, tmPeersPort
 	if datadir == "" {
 		home, err := os.UserHomeDir()
 		if err != nil {
-			panic("could not get home directory for data dir creation: " + err.Error())
+			fmt.Println("could not get home directory for data dir creation: " + err.Error())
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
			log.Fatalf("could not get home directory for data dir creation: %s",  err.Error())
```

stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 28]
```diff
@@ -175,7 +176,8 @@ func InitConfig(datadir, tmNode, persistentPeers, seeds, tmRPCPort, tmPeersPort
 		// ensure directory path made
 		err = os.MkdirAll(c.PocketConfig.DataDir+FS+ConfigDirName, os.ModePerm)
 		if err != nil {
-			panic(err)
+			fmt.Println(err)
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
			log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 29]
```diff
@@ -184,30 +186,36 @@ func InitConfig(datadir, tmNode, persistentPeers, seeds, tmRPCPort, tmPeersPort
 	if _, err := os.Stat(configFilepath); err == nil {
 		jsonFile, err = os.OpenFile(configFilepath, os.O_RDWR, os.ModePerm)
 		if err != nil {
-			panic("cannot open config json file: " + err.Error())
+			fmt.Println("cannot open config json file: " + err.Error())
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
			log.Fatalf("cannot open config json file: %s",  err.Error())
```

stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 30]
```diff
@@ -184,30 +186,36 @@ func InitConfig(datadir, tmNode, persistentPeers, seeds, tmRPCPort, tmPeersPort
...
 		}
 		b, err := ioutil.ReadAll(jsonFile)
 		if err != nil {
-			panic("cannot read config file: " + err.Error())
+			fmt.Println("cannot read config file: " + err.Error())
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
  log.Fatalf("cannot read config file: %s",  err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 31]
```diff
@@ -184,30 +186,36 @@ func InitConfig(datadir, tmNode, persistentPeers, seeds, tmRPCPort, tmPeersPort
...
 		}
 		err = json.Unmarshal(b, &c)
 		if err != nil {
-			panic("cannot read config file into json: " + err.Error())
+			fmt.Println("cannot read config file into json: " + err.Error())
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
  log.Fatalf("cannot read config file into json: %s",  err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 32]
```diff
@@ -184,30 +186,36 @@ func InitConfig(datadir, tmNode, persistentPeers, seeds, tmRPCPort, tmPeersPort
...
 		}
 	} else if os.IsNotExist(err) {
 		// if does not exist create one
 		jsonFile, err = os.OpenFile(configFilepath, os.O_RDWR|os.O_CREATE, os.ModePerm)
 		if err != nil {
-			panic("canot open/create config json file: " + err.Error())
+			fmt.Println("canot open/create config json file: " + err.Error())
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
  log.Fatalf("canot open/create config json file: %s",  err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 33]
```diff
@@ -184,30 +186,36 @@ func InitConfig(datadir, tmNode, persistentPeers, seeds, tmRPCPort, tmPeersPort
...
 		}
 		b, err := json.MarshalIndent(c, "", "    ")
 		if err != nil {
-			panic("cannot marshal default config into json: " + err.Error())
+			fmt.Println("cannot marshal default config into json: " + err.Error())
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
  log.Fatalf("cannot marshal default config into json: %s",  err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 34]
```diff
@@ -184,30 +186,36 @@ func InitConfig(datadir, tmNode, persistentPeers, seeds, tmRPCPort, tmPeersPort
...
 		}
 		// write to the file
 		_, err = jsonFile.Write(b)
 		if err != nil {
-			panic("cannot write default config to json file: " + err.Error())
+			fmt.Println("cannot write default config to json file: " + err.Error())
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
  log.Fatalf("cannot write default config to json file: %s",  err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 35]
```diff
@@ -239,17 +247,20 @@ func InitGenesis() {
 			// if does not exist create one
 			jsonFile, err := os.OpenFile(genFP, os.O_RDWR|os.O_CREATE, os.ModePerm)
 			if err != nil {
-				panic(err)
+				fmt.Println(err)
+				os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
  log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 36]
```diff
@@ -239,17 +247,20 @@ func InitGenesis() {
...
 			}
 			// write to the file
 			_, err = jsonFile.Write(newDefaultGenesisState())
 			if err != nil {
-				panic(err)
+				fmt.Println(err)
+				os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
  log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 37]
```diff
@@ -239,17 +247,20 @@ func InitGenesis() {
...
 			}
 			// close the file
 			err = jsonFile.Close()
 			if err != nil {
-				panic(err)
+				fmt.Println(err)
+				os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
  log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 38]
```diff
@@ -273,7 +285,8 @@ func InitTendermint() *node.Node {
 	})
 	logger, err := flags.ParseLogLevel(GlobalConfig.TendermintConfig.LogLevel, logger, "info")
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
  log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go (hunk 35 above)
Comment (edjroz) [inline app/config.go]:
```suggestion
                              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go (hunk 36 above)
Comment (edjroz) [inline app/config.go]:
```suggestion
                              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go (hunk 37 above)
Comment (edjroz) [inline app/config.go]:
```suggestion
                              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go (hunk 38 above)
Comment (edjroz) [inline app/config.go]:
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 39]
```diff
@@ -284,10 +297,12 @@ func InitTendermint() *node.Node {
 		return NewPocketCoreApp(logger, db, baseapp.SetPruning(store.PruneNothing))
 	})
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 40]
```diff
@@ -284,10 +297,12 @@ func InitTendermint() *node.Node {
...
 	}
 	if err := tmNode.Start(); err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
		log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 41]
```diff
@@ -319,32 +336,37 @@ func initFiles(address sdk.Address, password string, datadir string) string {
...
 		if password == "" {
-			panic("you must have a validator account password")
+			fmt.Println("you must have a validator account password")
+			os.Exit(1)
 		}
 		err := newKeybase(password)
 		if err != nil {
-			panic(err)
+			fmt.Println(err)
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
                     log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 42]
```diff
@@ -319,32 +336,37 @@ func initFiles(address sdk.Address, password string, datadir string) string {
...
 		}
 	}
 	if _, err := os.Stat(datadir + FS + GlobalConfig.TendermintConfig.PrivValidatorKey); err != nil {
 		if os.IsNotExist(err) {
 			password = privValKey(address, password)
 		} else {
-			panic(err)
+			fmt.Println(err)
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
                     log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 43]
```diff
@@ -319,32 +336,37 @@ func initFiles(address sdk.Address, password string, datadir string) string {
...
 		}
 	}
 	if _, err := os.Stat(datadir + FS + GlobalConfig.TendermintConfig.PrivValidatorState); err != nil {
 		if os.IsNotExist(err) {
 			privValState()
 		} else {
-			panic(err)
+			fmt.Println(err)
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
                     log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 44]
```diff
@@ -319,32 +336,37 @@ func initFiles(address sdk.Address, password string, datadir string) string {
...
 		}
 	}
 	if _, err := os.Stat(datadir + FS + GlobalConfig.TendermintConfig.NodeKey); err != nil {
 		if os.IsNotExist(err) {
 			nodeKey(address, password)
 		} else {
-			panic(err)
+			fmt.Println(err)
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
                     log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 45]
```diff
@@ -360,7 +382,8 @@ func InitPocketCoreConfig() {
 func MustGetKeybase() kb.Keybase {
 	keys, err := GetKeybase()
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
             log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 46]
```diff
@@ -400,7 +423,8 @@ func privValKey(address sdk.Address, password string) string {
 	}
 	res, err := (keys).ExportPrivateKeyObject(address, password)
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
             log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 47]
```diff
@@ -409,15 +433,18 @@ func privValKey(address sdk.Address, password string) string {
 	}
 	pvkBz, err := cdc.MarshalJSONIndent(privValKey, "", "  ")
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 48]
```diff
@@ -409,15 +433,18 @@ func privValKey(address sdk.Address, password string) string {
...
 	}
 	pvFile, err := os.OpenFile(GlobalConfig.PocketConfig.DataDir+FS+GlobalConfig.TendermintConfig.PrivValidatorKey, os.O_RDWR|os.O_CREATE, 0666)
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 49]
```diff
@@ -409,15 +433,18 @@ func privValKey(address sdk.Address, password string) string {
...
 	}
 	_, err = pvFile.Write(pvkBz)
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 50]
```diff
@@ -427,37 +454,44 @@ func nodeKey(address sdk.Address, password string) {
 	keys := MustGetKeybase()
 	res, err := (keys).ExportPrivateKeyObject(address, password)
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 51]
```diff
@@ -427,37 +454,44 @@ func nodeKey(address sdk.Address, password string) {
...
 	}
 	nodeKey := p2p.NodeKey{
 		PrivKey: res.PrivKey(),
 	}
 	pvkBz, err := cdc.MarshalJSONIndent(nodeKey, "", "  ")
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 52]
```diff
@@ -427,37 +454,44 @@ func nodeKey(address sdk.Address, password string) {
...
 	}
 	pvFile, err := os.OpenFile(GlobalConfig.PocketConfig.DataDir+FS+GlobalConfig.TendermintConfig.NodeKey, os.O_RDWR|os.O_CREATE, 0666)
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 53]
```diff
@@ -427,37 +454,44 @@ func nodeKey(address sdk.Address, password string) {
...
 	}
 	_, err = pvFile.Write(pvkBz)
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 54]
```diff
@@ -427,37 +454,44 @@ func nodeKey(address sdk.Address, password string) {
...
 	}
 }
 
 func privValState() {
 	pvkBz, err := cdc.MarshalJSONIndent(privval.FilePVLastSignState{}, "", "  ")
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 55]
```diff
@@ -427,37 +454,44 @@ func nodeKey(address sdk.Address, password string) {
...
 	}
 	pvFile, err := os.OpenFile(GlobalConfig.PocketConfig.DataDir+FS+GlobalConfig.TendermintConfig.PrivValidatorState, os.O_RDWR|os.O_CREATE, 0666)
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 56]
```diff
@@ -427,37 +454,44 @@ func nodeKey(address sdk.Address, password string) {
...
 	}
 	_, err = pvFile.Write(pvkBz)
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 57]
```diff
@@ -662,11 +705,13 @@ func GetPrivValFile() (file privval.FilePVKey) {
...
 	}
 	cb, err := keyb.GetCoinbase()
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 58]
```diff
@@ -662,11 +705,13 @@ func GetPrivValFile() (file privval.FilePVKey) {
 func newDefaultGenesisState() []byte {
 	keyb, err := GetKeybase()
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 59]
```diff
@@ -810,7 +856,8 @@ func ResetAll(dbDir, addrBookFile, privValKeyFile, privValStateFile string, logg
 	// recreate the dbDir since the privVal state needs to live there
 	err := cmn.EnsureDir(dbDir, 0700)
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 60]
```diff
@@ -782,7 +827,8 @@ func ResetWorldState(cmd *cobra.Command, args []string) {
 	if cmd.Flag("datadir").DefValue == cmd.Flag("datadir").Value.String() {
 		home, err := os.UserHomeDir()
 		if err != nil {
-			panic("could not get home directory for data dir creation: " + err.Error())
+			fmt.Println("could not get home directory for data dir creation: " + err.Error())
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
                      log.Fatalf("could not get home directory for data dir creation: %s", err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 61]
```diff
@@ -485,50 +519,59 @@ func NewHostedChains() *types.HostedBlockchains {
...
 	if err != nil {
-		panic(NewInvalidChainsError(err))
+		fmt.Println(NewInvalidChainsError(err))
+		os.Exit(1)
 	}
 	m := make(map[string]types.HostedBlockchain)
 	for _, chain := range hostedChainsSlice {
 		if err := nodesTypes.ValidateNetworkIdentifier(chain.ID); err != nil {
 			panic(fmt.Sprintf("invalid ID: %s in network identifier in %s file", chain.ID, GlobalConfig.PocketConfig.ChainsName))
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]: Rogue panic!!

```suggestion
                      log.Fatalf("invalid ID: %s in network identifier in %s file", chain.ID, GlobalConfig.PocketConfig.ChainsName)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 62]
```diff
@@ -632,7 +675,7 @@ func MakeCodec() {
 func Credentials() string {
 	bytePassword, err := terminal.ReadPassword(syscall.Stdin)
 	if err != nil {
-		panic(err)
+		fmt.Println(err)
```
Comment (edjroz) [inline app/config.go:636]: Should likely stop execution or it will panic on the return statement
```suggestion
		log.Fatal(err)
```

File: app/config.go [hunk 63]
```diff
@@ -485,50 +519,59 @@ func NewHostedChains() *types.HostedBlockchains {
...
-		panic(NewInvalidChainsError(err))
+		fmt.Println(NewInvalidChainsError(err))
+		os.Exit(1)
 	}
 	// close the file
 	err = jsonFile.Close()
 	if err != nil {
-		panic(NewInvalidChainsError(err))
+		fmt.Println(NewInvalidChainsError(err))
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
		log.Fatal(NewInvalidChainsError(err))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 64]
```diff
@@ -485,50 +519,59 @@ func NewHostedChains() *types.HostedBlockchains {
...
 	}
 	// unmarshal into the structure
 	var hostedChainsSlice []types.HostedBlockchain
 	err = json.Unmarshal(bz, &hostedChainsSlice)
 	if err != nil {
-		panic(NewInvalidChainsError(err))
+		fmt.Println(NewInvalidChainsError(err))
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
		log.Fatal(NewInvalidChainsError(err))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 65]
```diff
@@ -485,50 +519,59 @@ func NewHostedChains() *types.HostedBlockchains {
...
 	}
 	bz, err = ioutil.ReadAll(jsonFile)
 	if err != nil {
-		panic(NewInvalidChainsError(err))
+		fmt.Println(NewInvalidChainsError(err))
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
		log.Fatal(NewInvalidChainsError(err))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 66]
```diff
@@ -485,50 +519,59 @@ func NewHostedChains() *types.HostedBlockchains {
...
+			fmt.Println(NewInvalidChainsError(err))
+			os.Exit(1)
 		}
 	}
 	// reopen the file to read into the variable
 	jsonFile, err := os.OpenFile(chainsPath, os.O_RDWR|os.O_CREATE, os.ModePerm)
 	if err != nil {
-		panic(NewInvalidChainsError(err))
+		fmt.Println(NewInvalidChainsError(err))
+		os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
		log.Fatal(NewInvalidChainsError(err))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 67]
```diff
@@ -485,50 +519,59 @@ func NewHostedChains() *types.HostedBlockchains {
...
-			panic(NewInvalidChainsError(err))
+			fmt.Println(NewInvalidChainsError(err))
+			os.Exit(1)
 		}
 		// close the file
 		err = jsonFile.Close()
 		if err != nil {
-			panic(NewInvalidChainsError(err))
+			fmt.Println(NewInvalidChainsError(err))
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
		        log.Fatal(NewInvalidChainsError(err))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 68]
```diff
@@ -485,50 +519,59 @@ func NewHostedChains() *types.HostedBlockchains {
...
 		}
 		// generate hosted chains from user input
 		c := GenerateHostedChains()
 		// create dummy input for the file
 		res, err := json.MarshalIndent(c, "", "  ")
 		if err != nil {
-			panic(NewInvalidChainsError(err))
+			fmt.Println(NewInvalidChainsError(err))
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
		        log.Fatal(NewInvalidChainsError(err))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 69]
```diff
@@ -485,50 +519,59 @@ func NewHostedChains() *types.HostedBlockchains {
 		// if does not exist create one
 		jsonFile, err = os.OpenFile(chainsPath, os.O_RDWR|os.O_CREATE, os.ModePerm)
 		if err != nil {
-			panic(NewInvalidChainsError(err))
+			fmt.Println(NewInvalidChainsError(err))
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
		        log.Fatal(NewInvalidChainsError(err))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 70]
```diff
@@ -485,50 +519,59 @@ func NewHostedChains() *types.HostedBlockchains {
...
 		}
 		// write to the file
 		_, err = jsonFile.Write(res)
 		if err != nil {
-			panic(NewInvalidChainsError(err))
+			fmt.Println(NewInvalidChainsError(err))
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
		        log.Fatal(NewInvalidChainsError(err))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 71]
```diff
@@ -301,10 +316,12 @@ func InitKeyfiles() string {
...
 		// if not exist continue creating as other files may be missing
 		if os.IsNotExist(err) {
-			panic(fmt.Errorf("validator address not set! please run set-validator"))
+			fmt.Println(fmt.Errorf("validator address not set! please run set-validator"))
+			os.Exit(1)
 		} else {
 			//panic on other errors
-			panic(err)
+			fmt.Println(err)
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
			log.Fatal(err)

```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 72]
```diff
@@ -319,32 +336,37 @@ func initFiles(address sdk.Address, password string, datadir string) string {
 		fmt.Println("Initializing keybase: enter validator passphrase")
 		password = Credentials()
 		if password == "" {
-			panic("you must have a validator account password")
+			fmt.Println("you must have a validator account password")
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
		        log.Fatal("you must have a validator account password")
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 73]
```diff
@@ -301,10 +316,12 @@ func InitKeyfiles() string {
 	if _, err := os.Stat(datadir + FS + GlobalConfig.TendermintConfig.PrivValidatorKey); err != nil {
 		// if not exist continue creating as other files may be missing
 		if os.IsNotExist(err) {
-			panic(fmt.Errorf("validator address not set! please run set-validator"))
+			fmt.Println(fmt.Errorf("validator address not set! please run set-validator"))
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
			log.Fatal("validator address not set! please run set-validator")

```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go [hunk 74]
```diff
@@ -258,7 +269,8 @@ func InitGenesis() {
 func InitTendermint() *node.Node {
 	logger := log.NewTMLoggerWithColorFn(log.NewSyncWriter(os.Stdout), func(keyvals ...interface{}) term.FgBgColor {
 		if keyvals[0] != kitlevel.Key() {
-			panic(fmt.Sprintf("expected level key to be first, got %v", keyvals[0]))
+			fmt.Println(fmt.Sprintf("expected level key to be first, got %v", keyvals[0]))
+			os.Exit(1)
```
Comment (edjroz) [inline app/config.go]:
```suggestion
			log.Fatalf("expected level key to be first, got %v", keyvals[0])

```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go (hunk 32 above)
Comment (edjroz) [inline app/config.go]:
```suggestion
			log.Fatalf("canot open/create config json file: %s", err.Error())
```

stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go (hunk 33 above)
Comment (edjroz) [inline app/config.go]:
```suggestion
			log.Fatalf("cannot marshal default config into json: %s", err.Error())
```

stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go (hunk 34 above)
Comment (edjroz) [inline app/config.go]:
```suggestion
			log.Fatalf("cannot write default config to json file: %s", err.Error())
```

stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go (hunk 31 above)
Comment (edjroz) [inline app/config.go]:
```suggestion
			log.Fatalf("cannot marshal default config into json: %s", err.Error())
```

stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

File: app/config.go (hunk 30 above)
Comment (edjroz) [inline app/config.go]:
```suggestion
			log.Fatalf("cannot marshal default config into json: %s", err.Error())
```

stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

**Review by edjroz — CHANGES_REQUESTED** [review]
Solid contribution however there is a missing panic, consider the suggestions however only the panic is necessary
