### PR TITLE
reduce memory footprint for blocktxs & accounttxs

### LINKED ISSUE #1090: Resource Spike For query/AccountTxs
**Describe the bug**
```
I run an under powered non-validator on mainnet as a canary.  It does not provide or request relays.  Just a plain ole full node.
it is a standard Digitial Ocean $10/month, 1 vcpu, 2 gig of memory box.
I can reliably and repeatedly kill it with a single query command which will take it from a stable 226 mb of memory use.  to 1869 mb instantly at it will die shortly thereafter (next block for sure, sometimes instantly)
```
Before query
Screenshot from 2020-10-05 12-29-22
After query
Screenshot from 2020-10-05 12-33-46

NOTE: `The process kswapd0 is the process that manages virtual memory`
Observe Pocket Memory Spike from a single accountTxs Query

This did not return the result.

This sometimes results in:
`E[2020-10-05|16:53:25.292] data has been corrupted in last height of consensus WAL module=consensus err="DataCorruptionError[failed to read data: EOF (read: 15, wanted: 257)]" height=6566`

Might be related to #1089

### PR DESCRIPTION
**Pull request by edjroz**
Close #1090 
- [x] Add ordering for paging (default "desc")
- [x] Update tendermint to consume less memory when querying 
- [x] fixes bug in which tx's came nil in the page

### CODE REVIEW

**Review by oten91 — DISMISSED** [review]

File: app/cmd/rpc/query.go [hunk 1]
```diff
@@ -125,7 +128,7 @@ func ResultTxSearchToRPC(res *core_types.ResultTxSearch) RPCResultTxSearch {
 		return RPCResultTxSearch{}
 	}
 	rpcTxSearch := RPCResultTxSearch{
-		Txs:        make([]*RPCResultTx, res.TotalCount),
+		Txs:        make([]*RPCResultTx, 0, len(res.Txs)),
```
Comment (andrewnguyen22) [inline app/cmd/rpc/query.go]:
```suggestion
		Txs:        make([]*RPCResultTx, 0, res.TotalCount),
```

File: go.mod [hunk 2]
```diff
@@ -14,7 +14,7 @@ require (
 	github.com/stretchr/testify v1.6.1
 	github.com/tendermint/go-amino v0.15.0
 	github.com/tendermint/iavl v0.14.0
-	github.com/tendermint/tendermint v0.33.7
+	github.com/tendermint/tendermint v0.33.8
```
Comment (andrewnguyen22) [inline go.mod]:
```suggestion
	github.com/tendermint/tendermint v0.33.7
```

**Review by andrewnguyen22 — DISMISSED** [review]

**Review by oten91 — DISMISSED** [review]

**Review by oten91 — DISMISSED** [review]

**Review by oten91 — DISMISSED** [review]

**Review by andrewnguyen22 — DISMISSED** [review]

**Review by oten91 — DISMISSED** [review]

**Review by oten91 — APPROVED** [review]
