### PR TITLE
Ante handler and others

### LINKED ISSUE #590: Querying apps when there's none panics

### LINKED ISSUE #591: Node and app strings should use \t

### LINKED ISSUE #592: Supply returns wrong unstaked amount

### LINKED ISSUE #593: Querying block with no height leads to panic

### LINKED ISSUE #594: Querying account formatting issues
Querying an account that does not exist leads to this output:

```
Account: Account:
  Address:       
  Pubkey:        
  Coins:         
  AccountNumber: 0
  Sequence:      0
```

### LINKED ISSUE #595: Unstaking node panics
```panic: Ciphertext decryption failed```

### LINKED ISSUE #599: Transactions aren't subtracting the fee from the account

### LINKED ISSUE #600: Missed error check in newTX

### LINKED ISSUE #601: README Logo is gone

### LINKED ISSUE #606: Ante handler is missing, add back to POSMint and test

### PR DESCRIPTION
**Pull request by andrewnguyen22**
closes #590 
closes #591 
closes #592 
closes #593 
closes #594 
closes #595 
closes #599 
closes #600 
closes #601 
closes #606

### CODE REVIEW

**Review by oten91 — APPROVED** [review]

File: x/nodes/types/valUtil.go [hunk 1]
```diff
@@ -47,28 +47,21 @@ func UnmarshalValidator(cdc *codec.Codec, valBytes []byte) (validator Validator,
...
-	Status                  sdk.StakeStatus `json:"status" yaml:"status"`         // validator status (staked/unstaking/unstaked)
-	StakedTokens            sdk.Int         `json:"tokens" yaml:"tokens"`         // how many staked tokens
-	ServiceURL              string          `json:"service_url" yaml:"service_uRL"`
-	Chains                  []string        `json:"chains" yaml:"chains"`
+	Address                 sdk.Address     `json:"address" yaml:"address"`               // the hex address of the validator
+	PublicKey               string          `json:"public_key" yaml:"public_key"`         // the hex consensus public key of the validator
+	Jailed                  bool            `json:"jailed" yaml:"jailed"`                 // has the validator been jailed from staked status?
+	Status                  sdk.StakeStatus `json:"status" yaml:"status"`                 // validator status (staked/unstaking/unstaked)
+	StakedTokens            sdk.Int         `json:"tokens" yaml:"tokens"`                 // how many staked tokens
+	ServiceURL              string          `json:"service_url" yaml:"service_urL"`       // the url of the pocket-api
```
Comment (oten91) [inline x/nodes/types/valUtil.go]: change service_urL to service_url

**Review by oten91 — CHANGES_REQUESTED** [review]
