### PR TITLE
Challenge Transaction

### LINKED ISSUE #689: Challenge request for client
Clients need to be able to challenge incorrect data by providing a proof to the network

### PR DESCRIPTION
**Pull request by andrewnguyen22**
closes #689

### CODE REVIEW

File: app/cmd/rpc/rpc_test.go [hunk 1]
```diff
@@ -396,12 +396,14 @@ func TestRPC_Relay(t *testing.T) {
...
+		Data: expectedRequest,
+	}
 	// setup relay
 	relay := pocketTypes.Relay{
-		Payload: pocketTypes.Payload{
-			Data: expectedRequest,
-		},
-		Proof: pocketTypes.Proof{
+		Payload: payload,
+		Meta:    pocketTypes.RelayMeta{BlockHeight: 5}, // todo race condition here
```
Comment (luyzdeleon) [inline app/cmd/rpc/rpc_test.go:405]: Can you explain the race condition here?

File: app/query.go [hunk 2]
```diff
@@ -129,12 +129,12 @@ func QueryReceipts(addr string, height int64) (proofs []pocketTypes.Receipt, err
 	return pocket.QueryReceipts(Codec(), getTMClient(), a, height)
 }
 
-func QueryReceipt(blockchain, appPubKey, addr string, sessionblockHeight, height int64) (proof *pocketTypes.Receipt, err error) {
+func QueryReceipt(blockchain, appPubKey, addr, receipt string, sessionblockHeight, height int64) (proof *pocketTypes.Receipt, err error) {
```
Comment (luyzdeleon) [inline app/query.go]: Why querying a receipt (`pocketTypes.Receipt`) requires a `receipt string`

File: app/tx_test.go [hunk 3]
```diff
@@ -344,3 +345,174 @@ func TestClaimTx(t *testing.T) {
...
+			if res.Events["message.action"][0] != pocketTypes.EventTypeProof {
+				t.Fatal("proof message was not received afterward")
+			}
+			cleanup()
+			stopCli()
+		}
+	}
+}
+
+func NewValidChallengeProof(t *testing.T, privateKeys []crypto.PrivateKey, numOfChallenges int) (challenge []pocketTypes.ChallengeProofInvalidData) {
```
Comment (luyzdeleon) [inline app/tx_test.go:381]: Do we need a test to try the functionality of the "unsorted JSON" sorting?

File: x/pocketcore/keeper/claim.go [hunk 4]
```diff
@@ -49,26 +55,73 @@ func (k Keeper) SendClaimTx(ctx sdk.Ctx, n client.Client, keybase keys.Keybase,
...
+		return pc.NewNoEvidenceTypeErr(pc.ModuleName)
+	}
+	// get the session context
+	sessionContext, er := ctx.PrevCtx(claim.SessionBlockHeight)
+	if er != nil {
+		return sdk.ErrInternal(er.Error())
+	}
+	// if is not a pocket supported blockchain then return not supported error
+	if !k.IsPocketSupportedBlockchain(sessionContext, claim.Chain) {
+		return pc.NewChainNotSupportedErr(pc.ModuleName)
```
Comment (luyzdeleon) [inline x/pocketcore/keeper/claim.go:75]: Why does this error out?

File: x/pocketcore/keeper/proof.go [hunk 5]
```diff
@@ -20,33 +20,127 @@ func BeginBlocker(ctx sdk.Ctx, _ abci.RequestBeginBlock, k Keeper) {
...
+	addr := kp.GetAddress()
+	// get all mature (waiting period has passed) claims for your address
+	claims, err := k.GetMatureClaims(ctx, addr)
+	if err != nil {
+		ctx.Logger().Error(fmt.Sprintf("an error occured getting the mature claims in the ProofTX:\n%v", err))
+		return
+	}
+	// for every claim of the mature set
+	for _, claim := range claims {
+		// if the claim is found to be verified in the world state, you can delete it from the cache and not send again
```
Comment (luyzdeleon) [inline x/pocketcore/keeper/proof.go]: I think this step should be done after it's confirmed that the transaction was sent, cause if there's an error in any of the steps below, the data for a potential retry won't be there.

File: x/pocketcore/keeper/proof.go [hunk 6]
```diff
@@ -20,33 +20,127 @@ func BeginBlocker(ctx sdk.Ctx, _ abci.RequestBeginBlock, k Keeper) {
...
+		if _, found := k.GetReceipt(ctx, addr, claim.SessionHeader, claim.EvidenceType); found {
+			// remove from the local cache
+			pc.GetEvidenceMap().DeleteEvidence(claim.SessionHeader, claim.EvidenceType)
+			continue
+		}
+		// check to see if evidence is stored in cache
+		evidence, found := pc.GetEvidenceMap().GetEvidence(claim.SessionHeader, claim.EvidenceType)
+		if !found || evidence.Proofs == nil || len(evidence.Proofs) == 0 {
+			ctx.Logger().Info(fmt.Sprintf("the evidence object for evidence is not found, ignoring pending claim"))
```
Comment (luyzdeleon) [inline x/pocketcore/keeper/proof.go]: This log would be more useful if we somehow identified the ignored pending claim.

File: x/pocketcore/keeper/proof.go [hunk 7]
```diff
@@ -20,33 +20,127 @@ func BeginBlocker(ctx sdk.Ctx, _ abci.RequestBeginBlock, k Keeper) {
...
+	}
+	addr := addrs[0]
+	// get the claim for the address
+	claim, found := k.GetClaim(ctx, addr, proof.Leaf.SessionHeader(), proof.Leaf.EvidenceType())
+	// if the claim is not found for this claim
+	if !found {
+		return nil, pc.MsgClaim{}, pc.NewClaimNotFoundError(pc.ModuleName)
+	}
+	// validate the proof
+	ctx.Logger().Info(fmt.Sprintf("Generate psuedorandom proof with %d, at session height of %d", claim.TotalProofs, claim.SessionBlockHeight))
```
Comment (luyzdeleon) [inline x/pocketcore/keeper/proof.go]: Log would be more useful if you could identify somehow the MsgProof that it's being validated. Maybe by the app, or the session key?

File: x/pocketcore/types/service.go [hunk 8]
```diff
@@ -95,19 +122,60 @@ type Payload struct {
...
+	}
+	return json.Marshal(pay)
+}
+
+type RelayMeta struct {
+	BlockHeight int64 `json:"block_height"`
+}
+
+func (m RelayMeta) Validate(ctx sdk.Ctx) sdk.Error {
+	if ctx.BlockHeight()+5 < m.BlockHeight || ctx.BlockHeight()-5 > m.BlockHeight {
```
Comment (luyzdeleon) [inline x/pocketcore/types/service.go:168]: Can we make a configuration for the `+5` `-5` from the get-go?

File: x/pocketcore/types/service.go [hunk 9]
```diff
@@ -146,10 +210,18 @@ func (rr RelayResponse) HashString() string {
 }
 
 type relayResponse struct {
-	Signature   string `json:"signature"`
-	Response    string `json:"payload"`
-	RequestHash string `json:"request_hash"`
-	Proof       string `json:"Proof"`
+	Signature string `json:"signature"`
```
Comment (luyzdeleon) [inline x/pocketcore/types/service.go:213]: Why is there a private `relayResponse` type that looks exactly like a public `RelayResponse` type?

**Review by luyzdeleon — CHANGES_REQUESTED** [review]
Multiple questions and a few suggestions.

File: app/cmd/rpc/rpc_test.go (hunk 1 above)
Comment (andrewnguyen22) [reply app/cmd/rpc/rpc_test.go:405]: Block height is now needed to send a relay, and since block and creation time are unpredictable, it makes this test have a race -> `unsynced relay`

File: app/query.go (hunk 2 above)
Comment (andrewnguyen22) [reply app/query.go]: Ah that's actually receiptType -> `relay` or `challenge` will edit

File: app/tx_test.go (hunk 3 above)
Comment (andrewnguyen22) [reply app/tx_test.go:381]: Will add

File: x/pocketcore/keeper/claim.go (hunk 4 above)
Comment (andrewnguyen22) [reply x/pocketcore/keeper/claim.go:75]: Cause you can't create a claim an unsupported blockchain

File: x/pocketcore/keeper/proof.go (hunk 6 above)
Comment (andrewnguyen22) [reply x/pocketcore/keeper/proof.go]: Will fix

File: x/pocketcore/keeper/proof.go (hunk 7 above)
Comment (andrewnguyen22) [reply x/pocketcore/keeper/proof.go]: Will fix

File: x/pocketcore/types/service.go (hunk 8 above)
Comment (andrewnguyen22) [reply x/pocketcore/types/service.go:168]: Yes, but seems like a QOL separate issue kind of thing?

File: x/pocketcore/types/service.go (hunk 9 above)
Comment (andrewnguyen22) [reply x/pocketcore/types/service.go:213]: For overriding json marshalling

File: x/pocketcore/types/service.go (hunk 8 above)
Comment (andrewnguyen22) [reply x/pocketcore/types/service.go:168]: https://github.com/pokt-network/pocket-core/issues/705

**Review by luyzdeleon — APPROVED** [review]
