### PR TITLE
Fixed all applicable TODOs within project

### LINKED ISSUE #141: Remove redundant name declaration within RPC packages
Get*Relay*API (within the Relay RPC package) change to GetAPI

### LINKED ISSUE #142: Fix any TODOs within codebase (if possible)

### LINKED ISSUE #146: Need Info Struct For Every API Call
Every API call needs an Info Structure 'Get' call that can be parsed by pocket-core-api-docs

### PR DESCRIPTION
**Pull request by andrewnguyen22**
Also: 
Changed WriteResponse to WriteJSONRepsonse and deleted redundant function
&&
Changed GetInstance To Get for brevity

closes #142 
closes #141 
EDIT:
Now closes #146

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -71,8 +71,8 @@ func Print() {
 	fmt.Println("Pocket Core Configuration:\n", string(data)) // pretty print the pocket configuration
 }
 
-// "GetInstance()" returns the configuration object in a thread safe manner.
-func GetInstance() *config { // singleton structure to return the configuration object
+// "Get()" returns the configuration object in a thread safe manner.
+func Get() *config { // singleton structure to return the configuration object
```
Comment (iajrz) [inline config/config.go:75]: I'm having second thoughts about the "Get" nomenclature; while it looks good outside, because it's `module.Get`, things will get ugly if at any moment there's more than one singleton in a module. So - let's think about this a little, for the future. Researching on how other codebases do this will be good food.

File: rpc/client/routes.go [hunk 2]
```diff
@@ -17,43 +17,43 @@ func Routes() shared.Routes {
...
-		shared.Route{Name: "BCInfo", Method: "POST", Path: "/v1/pocket", HandlerFunc: BCInfo},
-		shared.Route{Name: "LatestBlock", Method: "POST", Path: "/v1/pocket/block", HandlerFunc: LatestBlock},
-		shared.Route{Name: "BlockByHash", Method: "POST", Path: "/v1/pocket/block/hash", HandlerFunc: BlockByHash},
-		shared.Route{Name: "BlkTXCountByHash", Method: "POST", Path: "/v1/pocket/block/hash/transaction_count", HandlerFunc: BlkTXCountByHash},
-		shared.Route{Name: "BlkByNum", Method: "POST", Path: "/v1/pocket/block/number", HandlerFunc: BlkByNum},
-		shared.Route{Name: "BlkCntByNum", Method: "POST", Path: "/v1/pocket/block/number/transaction_count", HandlerFunc: BlkCntByNum},
-		shared.Route{Name: "ProtVersion", Method: "POST", Path: "/v1/pocket/version", HandlerFunc: ProtVersion},
-		shared.Route{Name: "TxByHash", Method: "POST", Path: "/v1/pocket/transaction/hash", HandlerFunc: TxByHash},
+		shared.Route{Name: "Version", Method: "GET", Path: "/v1", HandlerFunc: Version},
+		// shared.Route{Name: "Account", Method: "POST", Path: "/v1/account", HandlerFunc: Account},
```
Comment (iajrz) [inline rpc/client/routes.go:21]: A lot of routes eliminated here - why?

Comment (andrewnguyen22) [reply rpc/client/routes.go:21]: Yes, so those routes are placeholders. Esentially (TODO) endpoints that I had already filled in! So I removed them because they are not necessary for MVP and they would be bloat for the dynamic doc I am creating

File: config/config.go (hunk 1 above)
Comment (andrewnguyen22) [reply config/config.go:75]: I agree! I renamed this back and forth like three times! Haha. But config.Get() seems to be more breif than config.GetInstance and config.GetConfig (redundant). So if you think that config.GetInstance() is better, feel free to rename!

Comment (andrewnguyen22) [reply config/config.go:75]: I also wanted to demonstrate that there is only one config instance throughout the lifetime of the program and config.GetInstance() kind of makes me think that there are multiple configuration instances available.

Comment (iajrz) [reply config/config.go:75]: Actually, GetInstance and Get suffer from the same problem; I was tentatively thinking `GlobalConfiguration` or `GlobalConfig` as names for the config's singleton getter, for instance. But as I mentioned, research would help us.

**Review by iajrz — APPROVED** [review]
lgtm

**Comment by iajrz** [comment]
Heh, I don't like how the "lgtm" has more visual representation than the review convos we had 🐻
