### PR TITLE
Block Signature handling fix for jailed validators and logs cleaning

### LINKED ISSUE #757: Absent validator message repeats
This error message repeats every block, should happen just once

```
I[2020-04-08|17:17:24.503] Absent validator 2ca5acb7ef55a89dba835fa3bbec5ff002119e79 (9d54477420519bb77ecc69818a9e5cf7bc44d8371e7998b696143fa89b17c6c4faac13ee1c) at height 11558, 100 missed, threshold 50 module=x/pos 
I[2020-04-08|17:17:24.503] Validator 2ca5acb7ef55a89dba835fa3bbec5ff002119e79 would have been slashed for downtime, but was either not found in store or already jailed module=x/pos s 
```

### PR DESCRIPTION
**Pull request by oten91**
closes #757

### CODE REVIEW

**Review by edjroz — DISMISSED** [review]

File: x/nodes/keeper/slash.go [hunk 1]
```diff
@@ -201,51 +201,56 @@ func (k Keeper) handleValidatorSignature(ctx sdk.Ctx, address crypto.Address, po
...
-	// if we are past the minimum height and the validator has missed too many blocks, punish them
-	if height > minHeight && signInfo.MissedBlocksCounter > maxMissed {
-		validator, found := k.GetValidator(ctx, addr)
-		if found && !validator.IsJailed() {
+	//check if validator is not already jailed
+	if !val.IsJailed() {
+		pubkey := val.PublicKey
+		// fetch signing info
+		signInfo, sifound := k.GetValidatorSigningInfo(ctx, addr)
+		if !sifound {
```
Comment (andrewnguyen22) [inline x/nodes/keeper/slash.go]: isFound

File: x/nodes/keeper/slash.go [hunk 2]
```diff
@@ -201,51 +201,56 @@ func (k Keeper) handleValidatorSignature(ctx sdk.Ctx, address crypto.Address, po
...
+		if missed {
+			ctx.EventManager().EmitEvent(
+				sdk.NewEvent(
+					types.EventTypeLiveness,
+					sdk.NewAttribute(types.AttributeKeyAddress, addr.String()),
+					sdk.NewAttribute(types.AttributeKeyMissedBlocks, fmt.Sprintf("%d", signInfo.MissedBlocksCounter)),
+					sdk.NewAttribute(types.AttributeKeyHeight, fmt.Sprintf("%d", height)),
+				),
+			)
+			//show log on first missing block sign after successful sign, if missed again this should not pop up and clutter the logs
```
Comment (andrewnguyen22) [inline x/nodes/keeper/slash.go]: go fmt

**Review by andrewnguyen22 — COMMENTED** [review]
This looks great! I'll approve, just two little things
